"""Generate bundled application metadata and third-party notices from local sources."""

import json
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
CLIENT = ROOT / "apps/client"


def generate():
    metadata = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--locked", "--offline", "--format-version", "1"],
        cwd=ROOT, text=True, encoding="utf-8",
    ))
    packages = {p["id"]: p for p in metadata["packages"]}
    nodes = {n["id"]: n for n in metadata["resolve"]["nodes"]}
    pending = [p["id"] for p in packages.values() if p["name"] in ("ts-ffi", "ts-gateway")]
    visited = set()
    while pending:
        package_id = pending.pop()
        if package_id in visited:
            continue
        visited.add(package_id)
        pending.extend(d["pkg"] for d in nodes[package_id]["deps"]
                       if any(k["kind"] != "dev" for k in d["dep_kinds"]))

    entries = []
    missing = []
    for package in sorted((packages[i] for i in visited), key=lambda p: (p["name"], p["version"])):
        directory = pathlib.Path(package["manifest_path"]).parent
        if package["id"] in metadata["workspace_members"]:
            continue
        files = set()
        for path in directory.rglob("*"):
            if path.is_file() and re.match(r"^(licen[sc]e|copying|notice)([._-].*)?$", path.name, re.I):
                files.add(path)
        if package.get("license_file"):
            files.add(directory / package["license_file"])
        # Vendored workspace members inherit the upstream root's dual license.
        vendor_root = ROOT / "vendor/tsclientlib"
        if directory.is_relative_to(vendor_root):
            files.update(vendor_root.glob("LICENSE*"))
        notices = []
        for path in sorted(files):
            notices.append(f"{path.name}\n\n{path.read_text(encoding='utf-8', errors='replace')}")
        if not notices:
            missing.append(package["name"])
        entries.append({
            "packages": [f"{package['name']} {package['version']}"],
            "text": "\n\n".join(filter(None, [package.get("license"),
                ", ".join(package.get("authors", [])), package.get("repository"), *notices])),
        })

    entries.append({"packages": ["Noto Sans / Noto Sans CJK"],
                    "text": (CLIENT / "assets/fonts/OFL.txt").read_text(encoding="utf-8")})
    entries.append({"packages": ["Nightcord Speak"], "text": "\n\n".join(
        (ROOT / filename).read_text(encoding="utf-8") for filename in ("LICENSE-MIT", "LICENSE-APACHE"))})
    destination = CLIENT / "assets/licenses/third_party.json"
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(json.dumps(entries, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    version = re.search(r"^version:\s*(\S+)", (CLIENT / "pubspec.yaml").read_text(encoding="utf-8"), re.M)[1]
    (CLIENT / "lib/models/app_info.dart").write_text(
        "// Generated by scripts/generate-about.py; regenerate after changing pubspec.yaml.\n"
        f"const appVersion = '{version}';\n"
        "const appProjectUrl = 'https://github.com/ChiyukiRuon/nightcord-speak';\n",
        encoding="utf-8",
    )
    print(f"Generated {len(entries)} notice entries ({destination.stat().st_size} bytes).")
    if missing:
        print("Packages without bundled license files: " + ", ".join(missing))


if __name__ == "__main__":
    generate()
